# Criatura lendária: Tiamat
Heloísa Fernandes Cano - T26
Aprendizado de Máquina - Professor Dr. Daniel Roberto Cassar

### Importando bibliotecas

In [2]:
import pandas as pd

### <a id = "leitura-do-arquivo"></a>Leitura do Arquivo de Dados

In [21]:
# define o nome do arquivo que vamos ler
arquivo = "consensus.csv"

# lê o arquivo
df = pd.read_csv(arquivo, header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,Family,Genus,Species,verbatimSpecies,WS_L_Fem,WS_U_Fem,WS_L_Mal,WS_U_Mal,WS_L,WS_U,...,EdgeAffinity,MoistureAffinity,DisturbanceAffinity,NumberOfHostplantFamilies,SoleHostplantFamily,PrimaryHostplantFamily,SecondaryHostplantFamily,EqualHostplantFamily,NumberOfHostplantAccounts,DateCreated
1,Hesperiidae,Abantis,Abantis arctomarginata,Abantis arctomarginata,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,Phyllanthaceae,NaN,NaN,NaN,1,3/9/2022 15:23
2,Hesperiidae,Abantis,Abantis bamptoni,Abantis bamptoni,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,Phyllanthaceae,NaN,NaN,NaN,1,3/9/2022 15:23
3,Hesperiidae,Abantis,Abantis bergeri,Abantis bergeri,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
4,Hesperiidae,Abantis,Abantis bicolor,Abantis bicolor,NaN,NaN,NaN,NaN,NaN,NaN,...,Edge-associated (strong),No evidence for moisture association,NaN,1,Malvaceae,NaN,NaN,NaN,1,3/9/2022 15:23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Riodinidae,Zelotaea,Zelotaea grosnyi,Zelotaea grosnyi,NaN,NaN,NaN,NaN,NaN,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12445,Riodinidae,Zelotaea,Zelotaea lya,Zelotaea lya,NaN,NaN,NaN,NaN,NaN,3.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12446,Riodinidae,Zelotaea,Zelotaea phasma,Zelotaea phasma,NaN,NaN,NaN,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12447,Riodinidae,Zemeros,Zemeros emesoides,Zemeros emesoides,NaN,NaN,NaN,NaN,3.5,4,...,Edge-associated (strong),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12448,Riodinidae,Zemeros,Zemeros flegyas,Zemeros flegyas,NaN,NaN,NaN,NaN,2.9,3.5,...,Edge-associated (weak),Both,Disturbance-associated (weak),1,Primulaceae,NaN,NaN,NaN,4,3/9/2022 15:23

### Renomeando colunas

Antes de prosseguirmos com os dados, precisamos renomear as colunas do dataframe, visto que elas estão numeradas. Porém, na primeira linha da tabela, temos as informações correspondentes sobre cada coluna. Vamos observá-las com o método `.iloc[0]`.

In [22]:
# .iloc[indice] -> imprime uma linha do data frame, dado seu indice
print(df.iloc[0])

0                        Family
1                         Genus
2                       Species
3               verbatimSpecies
4                      WS_L_Fem
5                      WS_U_Fem
6                      WS_L_Mal
7                      WS_U_Mal
8                          WS_L
9                          WS_U
10                     FW_L_Fem
11                     FW_U_Fem
12                     FW_L_Mal
13                     FW_U_Mal
14                         FW_L
15                         FW_U
16                          Jan
17                          Feb
18                          Mar
19                          Apr
20                          May
21                          Jun
22                          Jul
23                          Aug
24                          Sep
25                          Oct
26                          Nov
27                          Dec
28               FlightDuration
29                DiapauseStage
30                    Voltinism
31             OvipositionStyle
32               CanopyAffinity
33                 EdgeAffinity
34             MoistureAffinity
35          DisturbanceAffinity
36    NumberOfHostplantFamilies
37          SoleHostplantFamily
38       PrimaryHostplantFamily
39     SecondaryHostplantFamily
40         EqualHostplantFamily
41    NumberOfHostplantAccounts
42                  DateCreated
Name: 0, dtype: object

Agora que já sabemos o que é cada coluna, chegou a hora de renomeá-las. Primeiro, vamos utilizar o método `.columns`

In [26]:
df.columns = [
    "familia",
    "genero",
    "especie",
    "especie_original",
    "envergadura_min_femea_cm",
    "envergadura_max_femea_cm",
    "envergadura_min_macho_cm",
    "envergadura_max_macho_cm",
    "envergadura_min_cm",
    "envergadura_max_cm",
    "asa_anterior_min_femea_cm",
    "asa_anterior_max_femea_cm",
    "asa_anterior_min_macho_cm",
    "asa_anterior_max_macho_cm",
    "asa_anterior_min_cm",
    "asa_anterior_max_cm",
    "fenologia_jan",
    "fenologia_fev",
    "fenologia_mar",
    "fenologia_abr",
    "fenologia_mai",
    "fenologia_jun",
    "fenologia_jul",
    "fenologia_ago",
    "fenologia_set",
    "fenologia_out",
    "fenologia_nov",
    "fenologia_dez",
    "duracao_voo",
    "estagio_diapausa",
    "voltinismo",
    "estilo_oviposicao",
    "afinidade_dossel",
    "afinidade_borda",
    "afinidade_umidade",
    "afinidade_perturbacao",
    "num_familias_plantas_hospedeiras",
    "familia_unica_planta_hospedeira",
    "familia_principal_planta_hospedeira",
    "familia_secundaria_planta_hospedeira",
    "familia_igual_planta_hospedeira",
    "num_registros_plantas_hospedeiras",
    "data_criacao"
]
df = df.drop( index = 0 )
df

,familia,genero,especie,especie_original,envergadura_min_femea_cm,envergadura_max_femea_cm,envergadura_min_macho_cm,envergadura_max_macho_cm,envergadura_min_cm,envergadura_max_cm,...,afinidade_borda,afinidade_umidade,afinidade_perturbacao,num_familias_plantas_hospedeiras,familia_unica_planta_hospedeira,familia_principal_planta_hospedeira,familia_secundaria_planta_hospedeira,familia_igual_planta_hospedeira,num_registros_plantas_hospedeiras,data_criacao
0,Family,Genus,Species,verbatimSpecies,WS_L_Fem,WS_U_Fem,WS_L_Mal,WS_U_Mal,WS_L,WS_U,...,EdgeAffinity,MoistureAffinity,DisturbanceAffinity,NumberOfHostplantFamilies,SoleHostplantFamily,PrimaryHostplantFamily,SecondaryHostplantFamily,EqualHostplantFamily,NumberOfHostplantAccounts,DateCreated
1,Hesperiidae,Abantis,Abantis arctomarginata,Abantis arctomarginata,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,Phyllanthaceae,NaN,NaN,NaN,1,3/9/2022 15:23
2,Hesperiidae,Abantis,Abantis bamptoni,Abantis bamptoni,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,Phyllanthaceae,NaN,NaN,NaN,1,3/9/2022 15:23
3,Hesperiidae,Abantis,Abantis bergeri,Abantis bergeri,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
4,Hesperiidae,Abantis,Abantis bicolor,Abantis bicolor,NaN,NaN,NaN,NaN,NaN,NaN,...,Edge-associated (strong),No evidence for moisture association,NaN,1,Malvaceae,NaN,NaN,NaN,1,3/9/2022 15:23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Riodinidae,Zelotaea,Zelotaea grosnyi,Zelotaea grosnyi,NaN,NaN,NaN,NaN,NaN,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12445,Riodinidae,Zelotaea,Zelotaea lya,Zelotaea lya,NaN,NaN,NaN,NaN,NaN,3.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12446,Riodinidae,Zelotaea,Zelotaea phasma,Zelotaea phasma,NaN,NaN,NaN,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12447,Riodinidae,Zemeros,Zemeros emesoides,Zemeros emesoides,NaN,NaN,NaN,NaN,3.5,4,...,Edge-associated (strong),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/9/2022 15:23
12448,Riodinidae,Zemeros,Zemeros flegyas,Zemeros flegyas,NaN,NaN,NaN,NaN,2.9,3.5,...,Edge-associated (weak),Both,Disturbance-associated (weak),1,Primulaceae,NaN,NaN,NaN,4,3/9/2022 15:23

## Referências